# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM node:18-alpine AS client-builder


WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=client-builder /app/dist .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]



